const Home = () => {
	return (
		<div className='p-8 overflow-hidden'>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
		</div>
	);
};

export default Home;
