const Home = () => {
	return (
		<div className='p-4 overflow-hidden bg-yellow-200'>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
			<p>home</p>
		</div>
	);
};

export default Home;
